create table if not exists public.legal_acceptances (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  age_band text not null check (age_band in ('14-17', '18+')),
  terms_version text not null,
  privacy_version text not null,
  accepted_at timestamptz not null default now(),
  unique (user_id, terms_version, privacy_version)
);

alter table public.legal_acceptances enable row level security;

drop policy if exists "Users can read their own legal acceptances"
  on public.legal_acceptances;

create policy "Users can read their own legal acceptances"
  on public.legal_acceptances
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create or replace function public.record_signup_legal_acceptance()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  signup_age_band text := new.raw_user_meta_data ->> 'age_band';
  signup_terms_version text := new.raw_user_meta_data ->> 'terms_version';
  signup_privacy_version text := new.raw_user_meta_data ->> 'privacy_version';
begin
  if signup_age_band not in ('14-17', '18+')
    or nullif(signup_terms_version, '') is null
    or nullif(signup_privacy_version, '') is null then
    raise exception 'Age eligibility and legal acceptance are required';
  end if;

  insert into public.legal_acceptances (
    user_id,
    age_band,
    terms_version,
    privacy_version,
    accepted_at
  ) values (
    new.id,
    signup_age_band,
    signup_terms_version,
    signup_privacy_version,
    now()
  );

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_record_legal_acceptance on auth.users;
create trigger on_auth_user_created_record_legal_acceptance
  after insert on auth.users
  for each row execute procedure public.record_signup_legal_acceptance();

revoke all on table public.legal_acceptances from anon;
revoke insert, update, delete on table public.legal_acceptances from authenticated;
